#pragma once

#define THREADED_UPDATE false 
#define MAX_MOVE_COUNT 2048U

#define IMPORT_EXPORT_MAP_DIR "assets/"


#define UPDATE_SEG_W 16
#define UPDATE_SEG_H 16

#define bSTEAM_CONDENSATES false
#define STEAM_CONDENSATION_CHANCE 0.001f
#define STEAM_MIN_AGE_TO_CONDENSATE 90

#define DIRT_TO_GRASS_REQ_TIME 120

#define COMPRESSED_DIRT_CRUMBLE_PROBABILITY 0.00001f

#define bREACTION_LAVA_WATER_STEAM true 
#define bREACTION_LAVA_WATER_COBBLE true 

#define ACID_REACTION_PROBABILITY 0.05f
#define ACID_SMOKE_PROBABILITY 0.1f

#define TREE_MIN_INITIAL_SIZE 15
#define TREE_MAX_INTTIAL_SIZE 25

#define TREE_MIN_BRANCH_SIZE 5
#define TREE_MAX_BRANCH_SIZE 10
#define TREE_BRANCH_GROW_CHANCE 0.5f
#define TREETOP_RADIUS 5

#define LEAF_DUPE_CHANCE 0.5f

#define MAX_FIRE_LIFETIME 30 
#define MIN_FIRE_LIFETIME 10 
    
#define SMOKE_CHANCE 0.05f

#define FIRE_COLOR_BLEND_AREA_HEIGHT 5
